version: "3.7"
services:
  api:
    build:
      context: ./api
    ports:
      - "3005:3005"
    environment:
      - DB_USERNAME=db_user
      - DB_PASSWORD=db_pass
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=jonar_shop
      - APP_PORT=3005
      - JWT_SECRET=B[T@_6_-M2ux\^u),<7D9hsu99x.2-}bX_2bUXgnW?#5YT*cn$d{HjvBW^#Jfs]j
    depends_on:
      - "db"
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_pass
      - POSTGRES_DB=jonar_shop
    ports:
      - "5432:5432"

  ui:
    build:
      context: ./client
    ports:
      - "3000:3000"
    environment:
      - BASE_API=api:3005    
    depends_on:
      - "api"